// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWwln7EbUc7wu9nCbVQ4-my-TgWEiwEeU',
    appId: '1:703570535771:web:84c8eb935cec01a066667e',
    messagingSenderId: '703570535771',
    projectId: 'u-mind-3cda9',
    authDomain: 'u-mind-3cda9.firebaseapp.com',
    storageBucket: 'u-mind-3cda9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD8HTONyGsJWWa7yznNXV5UOyDIdqpOpY',
    appId: '1:703570535771:android:81955e2760b09eef66667e',
    messagingSenderId: '703570535771',
    projectId: 'u-mind-3cda9',
    storageBucket: 'u-mind-3cda9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFuexwxVSY8GHRaYNS3kLgxc8BhjLwYMw',
    appId: '1:703570535771:ios:c457524df16f736066667e',
    messagingSenderId: '703570535771',
    projectId: 'u-mind-3cda9',
    storageBucket: 'u-mind-3cda9.appspot.com',
    iosBundleId: 'com.example.umind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFuexwxVSY8GHRaYNS3kLgxc8BhjLwYMw',
    appId: '1:703570535771:ios:c457524df16f736066667e',
    messagingSenderId: '703570535771',
    projectId: 'u-mind-3cda9',
    storageBucket: 'u-mind-3cda9.appspot.com',
    iosBundleId: 'com.example.umind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWwln7EbUc7wu9nCbVQ4-my-TgWEiwEeU',
    appId: '1:703570535771:web:84218b499fc5e0d366667e',
    messagingSenderId: '703570535771',
    projectId: 'u-mind-3cda9',
    authDomain: 'u-mind-3cda9.firebaseapp.com',
    storageBucket: 'u-mind-3cda9.appspot.com',
  );
}
